### ISSUE TITLE
Documentation for Joystick support

### ISSUE THREAD

**Issue by jesusmgg** [crashkonijn/AirController#1]
On the readme, joystick support is mentioned:

> Out of the box support for buttons, buttons with int values and joysticks

But I cannot find any way to implement them or any mention in the wiki, the only part that looks like something is this:

> `<div id="not_joined_joystick" air-joystick="joystick" class="button">Joystick</div>`

But I doesn't send anything, in fact I tried to look at the JS source and didn't find anything.

Are joysticks supported? I also tried to implement them with pans but pans doesn't work correctly to me in mobile phones.

**Comment by crashkonijn** [comment]
@jesusmgg I did support Joysticks at one point, but I removed them because AirConsole doesn't like joysticks being used.

I think if you look back some commits it should be in there somewhere.

Also I must note that I'm currently working on a new (and much better) controller/JS implementation.

**Comment by crashkonijn** [comment]
If you're interested where the new controller is going, I uploaded an initial (undocumented) version: https://github.com/crashkonijn/air-controller-vue

**Comment by jesusmgg** [comment]
I am indeed very interested, I'll check it out, thanks!
